name: intercounty_tennis_env
channels:
  - conda-forge
dependencies:
  - python=3.10
  - pandas
  - numpy
  - selenium
  - jupyterlab
  - streamlit
  - beautifulsoup4
  - lxml
  - matplotlib
  - ipykernel
  - pytest
  - rapidfuzz
  - pyarrow
  - pip
  - pip:
      - scikit-learn
      - webdriver-manager
      - gender_guesser
